spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ssc
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: mongodb+srv://gamgam0330:aIjRXSKd0pB8iI8U@mycluster.y5s89rb.mongodb.net/?retryWrites=true&w=majority&appName=myCluster
      database: myCluster
      #database: myCluster
      #password: aIjRXSKd0pB8iI8U



  kafka: #Kafka
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumerGroup1
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: kafkaTest

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    org.hibernate.sql: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

jwt:
  secret: sithubzz6qwerasfdsdfsfffcvgffdbbberdddwqedq2retwd
