spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/geeks
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: root


  kafka: #kafka??
    bootstrap-servers: kafka:9092
    consumer:
      group-id: consumerGroup1
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: kafkaTest

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    org.hibernate.sql: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true